-- 코드를 작성해주세요
SELECT I.ITEM_ID,
        I.ITEM_NAME,
        I.RARITY
FROM ITEM_INFO I
LEFT JOIN ITEM_TREE T
ON I.ITEM_ID=T.ITEM_ID
WHERE I.ITEM_ID NOT IN (SELECT DISTINCT(IFNULL(PARENT_ITEM_ID,-1)) FROM ITEM_TREE)
ORDER BY I.ITEM_ID DESC;

