-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID=O.ANIMAL_ID
WHERE I.ANIMAL_ID IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY DATEDIFF(O.DATETIME,I.DATETIME) DESC
LIMIT 2;