-- 코드를 입력하세요
SELECT USER_ID,
        NICKNAME,
         CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', COALESCE(U.STREET_ADDRESS2, '')) '전체주소',
        CONCAT(SUBSTR(TLNO,1,3),'-', SUBSTR(TLNO,4,4), '-', SUBSTR(TLNO,8,4)) AS '전화번호'
FROM USED_GOODS_USER U
LEFT JOIN USED_GOODS_BOARD B
ON U.USER_ID=B.WRITER_ID
GROUP BY U.USER_ID
HAVING COUNT(BOARD_ID)>=3
ORDER BY U.USER_ID DESC;