-- 코드를 입력하세요
SELECT CAR_ID,
        CASE WHEN STR_TO_DATE('2022-10-16','%Y-%m-%d') BETWEEN START_DATE AND END_DATE
        THEN '대여중'
        ELSE'대여 가능' 
        END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC;
