-- 코드를 작성해주세요
SELECT YEAR(ED.DIFFERENTIATION_DATE) YEAR,
    (MC.MAXSC-ED.SIZE_OF_COLONY) YEAR_DEV,
    ED.ID
FROM ECOLI_DATA ED
LEFT JOIN (SELECT YEAR(DIFFERENTIATION_DATE) YEAR,MAX(SIZE_OF_COLONY) MAXSC FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) MC ON YEAR(ED.DIFFERENTIATION_DATE)=MC.YEAR
ORDER BY YEAR, YEAR_DEV;